# -*- coding: utf-8 -*-
"""metrocard.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-y0ktgzRquGUFbCQ7X7Vhlgipsb458gt
"""

import numpy as np

x=127

y=2.75

z=x/y

print(z)